FROM pactfoundation/pact-broker:2.79.0.1

#https://hub.docker.com/r/pactfoundation/pact-broker
ENV PACT_BROKER_PORT=9292
# change when final db is available
ENV PACT_BROKER_DATABASE_ADAPTER="sqlite"
ENV PACT_BROKER_LOG_LEVEL="INFO"
ENV PACT_BROKER_SQL_LOG_LEVEL="DEBUG"